export const departments = [
	{ value: "Sales", label: "Sales" },
	{ value: "Marketing", label: "Marketing" },
	{ value: "Engineering", label: "Engineering" },
	{ value: "Human Resources", label: "Human Resources" },
	{ value: "Legal", label: "Legal" },
];

export const states = [
	{ value: "Alabama", label: "Alabama" },
	{ value: "Alaska", label: "Alaska" },
	{ value: "Arizona", label: "Arizona" },
	{ value: "Arkansas", label: "Arkansas" },
	{ value: "California", label: "California" },
	{ value: "Colorado", label: "Colorado" },
	{ value: "Connecticut", label: "Connecticut" },
	{ value: "Delaware", label: "Delaware" },
	{ value: "Florida", label: "Florida" },
	{ value: "Georgia", label: "Georgia" },
	{ value: "Hawaii", label: "Hawaii" },
	{ value: "Idaho", label: "Idaho" },
	{ value: "Illinois", label: "Illinois" },
	{ value: "Indiana", label: "Indiana" },
	{ value: "Iowa", label: "Iowa" },
	{ value: "Kansas", label: "Kansas" },
	{ value: "Kentucky", label: "Kentucky" },
	{ value: "Louisiana", label: "Louisiana" },
	{ value: "Maine", label: "Maine" },
	{ value: "Maryland", label: "Maryland" },
	{ value: "Massachusetts", label: "Massachusetts" },
	{ value: "Michigan", label: "Michigan" },
	{ value: "Minnesota", label: "Minnesota" },
	{ value: "Mississippi", label: "Mississippi" },
	{ value: "Missouri", label: "Missouri" },
	{ value: "Montana", label: "Montana" },
	{ value: "Nebraska", label: "Nebraska" },
	{ value: "Nevada", label: "Nevada" },
	{ value: "New Hampshire", label: "New Hampshire" },
];
